version: '2'

services:
  db:
    image: postgres:9.5
    env_file: .env
    volumes:
      - diot_data_dev:/var/lib/postgresql/data/pgdata

  diot_back:
    build:
      context: ./Source
    env_file: .env
