# Generated by Django 2.0.7 on 2019-08-08 02:22

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiodDiveceTypes',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date_of_launch', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DiotDivice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dh11Sensor',
            fields=[
                ('ditoDiviceId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diot_api.DiotDivice')),
                ('states', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MagnetiqSensor',
            fields=[
                ('ditoDiviceId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diot_api.DiotDivice')),
                ('states', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Mq2Sensor',
            fields=[
                ('ditoDiviceId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diot_api.DiotDivice')),
                ('states', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='diotdivice',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diot_api.DiodDiveceTypes'),
        ),
        migrations.AddField(
            model_name='diotdivice',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
