# Generated by Django 2.1.1 on 2019-09-05 13:31

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiotDiveceTypes',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date_of_launch', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=5)),
                ('publish_chanels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('subcribers_chanels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='DiotDivice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('publish_topics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('subcribers_topics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diot_api.DiotDiveceTypes')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
