# Generated by Django 2.0.7 on 2019-08-08 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diotdivice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
